## Exercici 5

* Gestión de errores con async/await: Modifica la función del ejercicio 4 para que capture cualquier posible error utilizando un bloque try/catch.

### solucion propuesta

![Ejercicio5](https://github.com/Luiso-o/Ejercicio-S2.1-Javascript-I/assets/128043647/7f473e00-d6f4-46ac-863c-ed60f5fed8ad)
